idf_component_register(
    SRCS
        "app_main.cpp"
        "app_owner.cpp"
        "app_console.cpp"
        "app_display.cpp"
        "app_input.cpp"
        "app_js.cpp"
        "js_stdlib_table.c"
        "app_power.cpp"
        "app_reader.cpp"
        "app_storage.cpp"
        "app_ui.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        console
        esp_driver_usb_serial_jtag
        esp_timer
        s3paper_core
        s3paper_m5
        s3paper_storage
        s3paper_runtime
        fatfs
        sdmmc
        esp_driver_sdspi
        mquickjs
)
