idf_component_register(
    SRCS
        "app_main.cpp"
        "app_owner.cpp"
        "app_console.cpp"
        "app_display.cpp"
        "app_input.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        console
        esp_driver_usb_serial_jtag
        esp_timer
        s3paper_core
        s3paper_m5
)
