idf_component_register(
    SRCS
        "app_main.cpp"
        "wasm_runtime_service.cpp"
        "wasm_host_api.cpp"
        "wasm_runner.cpp"
        "js_command.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        espressif__wasm-micro-runtime
        console
        pthread
    PRIV_REQUIRES
        esp_driver_gpio
        esp_timer
        esp_psram
        heap
    EMBED_FILES
        "quickjs.wasm"
)
