idf_component_register(
    SRCS
        "app_main.c"
        "bench_server.c"
        "wifi_app.c"
        "wifi_console.c"
    INCLUDE_DIRS "."
    PRIV_REQUIRES
        nvs_flash
        esp_event
        esp_netif
        esp_wifi
        esp_http_server
        console
        driver
        esp_driver_usb_serial_jtag
        esp_timer
    EMBED_TXTFILES
        "assets/index.html"
        "assets/app.js"
)
