/* s3jsc: host compiler for the reader's JS apps (task ibe5).
 *
 * Compiles an ES5 source file against the SAME s3 stdlib (atoms!) the
 * device runs, emits relocated 32-bit bytecode as a C header for
 * EMBED-style inclusion. Pinned to the runtime by construction: it links
 * the vendored engine sources from components/mquickjs directly.
 *
 * Build and run via tools/js/build_bytecode_apps.sh. The stub functions
 * exist only to satisfy the stdlib table's symbol references; a
 * compilation context never calls them (mqjs.c: "the actual content of
 * the stdlib does not matter... the atoms for the parsing are defined").
 *
 * usage: s3jsc <in.js> <out.h> <symbol>
 */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "mquickjs.h"

#define STUB(name)                                                         \
    static JSValue name(JSContext *ctx, JSValue *this_val, int argc,       \
                        JSValue *argv) {                                   \
        (void)ctx; (void)this_val; (void)argc; (void)argv;                 \
        return JS_UNDEFINED;                                               \
    }

STUB(js_print)
STUB(js_gc)
STUB(js_load)
STUB(js_setTimeout)
STUB(js_clearTimeout)
STUB(js_date_now)
STUB(js_performance_now)
STUB(js_millis)
STUB(js_s3_version)
STUB(js_s3_reset)
STUB(js_s3_text)
STUB(js_s3_row)
STUB(js_s3_col)
STUB(js_s3_spacer)
STUB(js_s3_divider)
STUB(js_s3_progress)
STUB(js_s3_list)
STUB(js_s3_region)
STUB(js_s3_add_child)
STUB(js_s3_set_text)
STUB(js_s3_set_progress)
STUB(js_s3_config)
STUB(js_s3_present)
STUB(js_s3_library_count)
STUB(js_s3_library_line)
STUB(js_s3_embedded_line)
STUB(js_s3_open_book)
STUB(js_s3_book_open)
STUB(js_s3_book_title)
STUB(js_s3_book_line_count)
STUB(js_s3_book_line)
STUB(js_s3_book_next)
STUB(js_s3_book_prev)
STUB(js_s3_book_progress)

/* 64-bit host build of the SAME stdlib definition (generated without
   -m32 by build_bytecode_apps.sh). */
#include "s3_stdlib_host.h"

static void log_to_stderr(void *opaque, const void *buf, size_t len) {
    (void)opaque;
    fwrite(buf, 1, len, stderr);
}

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: s3jsc <in.js> <out.h> <symbol>\n");
        return 1;
    }
#if JSW != 8
    fprintf(stderr, "s3jsc must be built as a 64-bit host tool\n");
    return 1;
#else
    FILE *in = fopen(argv[1], "rb");
    if (in == NULL) {
        perror(argv[1]);
        return 1;
    }
    fseek(in, 0, SEEK_END);
    const long src_len = ftell(in);
    fseek(in, 0, SEEK_SET);
    char *src = malloc((size_t)src_len + 1);
    if (fread(src, 1, (size_t)src_len, in) != (size_t)src_len) {
        fprintf(stderr, "short read\n");
        return 1;
    }
    src[src_len] = '\0';
    fclose(in);

    const size_t mem_size = 4u << 20;
    void *mem = malloc(mem_size);
    JSContext *ctx = JS_NewContext2(mem, mem_size, &js_stdlib, 1);
    if (ctx == NULL) {
        fprintf(stderr, "JS_NewContext2 failed\n");
        return 1;
    }
    JS_SetLogFunc(ctx, log_to_stderr);
    const JSValue parsed =
        JS_Parse(ctx, src, (size_t)src_len, argv[1], JS_EVAL_STRIP_COL);
    if (JS_IsException(parsed)) {
        const JSValue err = JS_GetException(ctx);
        JS_PrintValueF(ctx, err, JS_DUMP_LONG);
        fprintf(stderr, "\nparse failed: %s\n", argv[1]);
        return 1;
    }
    JSBytecodeHeader32 hdr;
    const uint8_t *data = NULL;
    uint32_t data_len = 0;
    if (JS_PrepareBytecode64to32(ctx, &hdr, &data, &data_len, parsed) != 0) {
        fprintf(stderr, "64->32 bytecode conversion failed\n");
        return 1;
    }

    FILE *out = fopen(argv[2], "wb");
    if (out == NULL) {
        perror(argv[2]);
        return 1;
    }
    fprintf(out,
            "/* generated by tools/js/s3jsc.c from %s - do not edit */\n"
            "#pragma once\n\n"
            "static const unsigned char %s[] = {\n",
            argv[1], argv[3]);
    const uint8_t *hdr_bytes = (const uint8_t *)&hdr;
    uint32_t col = 0;
    for (uint32_t i = 0; i < sizeof(hdr); ++i) {
        fprintf(out, "0x%02x,%s", hdr_bytes[i],
                (++col % 12) == 0 ? "\n" : " ");
    }
    for (uint32_t i = 0; i < data_len; ++i) {
        fprintf(out, "0x%02x,%s", data[i], (++col % 12) == 0 ? "\n" : " ");
    }
    fprintf(out, "\n};\n");
    fclose(out);
    fprintf(stderr, "%s: %u bytecode bytes -> %s\n", argv[1],
            (unsigned)(sizeof(hdr) + data_len), argv[2]);
    JS_FreeContext(ctx);
    free(mem);
    free(src);
    return 0;
#endif
}
