#!/usr/bin/env python3
"""ESP-55 Phase 0: embed the dice and settings sections of pulp.js as byte
arrays in main/js_measure_src.h so the `js measure` console op can time
JS_Eval of realistic app-module source on the device.

Temporary instrumentation: superseded in Phase 3 by the real load(path).
Regenerate after editing pulp.js: sections are cut at `// ---- name --`.
"""
import re, sys, os

ROOT = "/home/manuel/code/wesen/go-go-golems/esp32-s3-m5/0114-papers3-pulp-os"
PULP = os.path.join(ROOT, "tools/js/apps/pulp.js")
OUT = os.path.join(ROOT, "main/js_measure_src.h")
BANNER = re.compile(r"^// -{4,}\s*(\S+)\s*-{2,}\s*$")
WANT = {"dice": "kMeasureDice", "settings": "kMeasureSettings"}

def split(src):
    sections, name, buf = {}, "prelude", []
    for line in src.splitlines(keepends=True):
        m = BANNER.match(line.rstrip("\n"))
        if m:
            sections[name] = "".join(buf)
            name, buf = m.group(1), [line]
        else:
            buf.append(line)
    sections[name] = "".join(buf)
    return sections

def emit(f, sym, body):
    data = body.encode() + b"\0"
    f.write(f"static const unsigned char {sym}[] = {{\n")
    for i in range(0, len(data), 12):
        f.write("    " + ", ".join(f"0x{b:02x}" for b in data[i:i+12]) + ",\n")
    f.write("};\n")
    f.write(f"static const unsigned {sym}Len = {len(data) - 1};"
            "  /* excludes NUL */\n\n")

def main():
    sections = split(open(PULP).read())
    with open(OUT, "w") as f:
        f.write("// generated by ESP-55 scripts/03-gen-measure-src.py"
                " - do not edit.\n"
                "// Phase 0 measurement sources (dice + settings sections"
                " of pulp.js).\n#pragma once\n\n")
        for name, sym in WANT.items():
            if name not in sections:
                sys.exit(f"section {name} not found in pulp.js")
            emit(f, sym, sections[name])
    print(f"wrote {OUT}: " + ", ".join(
        f"{n}={len(sections[n])}B" for n in WANT))

if __name__ == "__main__":
    main()
