[env:m5dial]
platform = espressif32@6.7.0
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    m5stack/M5Dial@^1.0.3
    bblanchon/ArduinoJson@^7.0.4
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
