#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
JS_DIR="$ROOT/0102-esp32-p4-visual-quickjs-repl/js"

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <example-name|example-path>" >&2
  echo "example: $0 hello-api" >&2
  exit 2
fi

example="$1"
if [[ "$example" != */* ]]; then
  example="$JS_DIR/examples/$example.js"
elif [[ "$example" != /* ]]; then
  example="$ROOT/$example"
fi

if [[ ! -f "$example" ]]; then
  echo "example not found: $example" >&2
  exit 1
fi

cat <<'HEADER'
// Bundled portable picoOS example.
// Device contract: requires print(...args), millis(), and gc() globals.
// Generated by js/tests/bundle-example.sh; do not edit this generated output.

HEADER
cat \
  "$JS_DIR/lib/00-core.js" \
  "$JS_DIR/lib/10-screen.js" \
  "$JS_DIR/lib/20-os-sim.js" \
  "$JS_DIR/lib/30-ui-runtime.js" \
  "$example"
